apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hqmuot876-go 
  janus-idp.io/tekton: hqmuot876-go
  backstage.io/kubernetes-id: hqmuot876-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hqmuot876-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml