apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hqmuot876-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hqmuot876-go 
  name: hqmuot876-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hqmuot876-go 
